### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by GwenTheKween** [Pythia3431/Delphinium#1]
Hi. 

I'm interested in this project, but before I can comfortably use and/or suggest it, I need to know what license did you have in mind, as I can basically only use software that explicitly states that can be used in a commercial environment without the need to make the final product open source as well. 

If you don't know where to start, GPL, Apache and MIT licenses might be worth checking out

**Comment by xzinkus** [comment]
Thanks for this comment, I hope you're able to get good use out of the tool!
